version: '3.6'

services:
  database:
    image: "postgres"
    env_file:
      - database.env
    ports:
    - 5432
    volumes:
    - ./migrations/20211006222441_create_wallet_service.up.sql:/docker-entrypoint-initdb.d/20211006222441_create_wallet_service.up.sql



  server:
    image: walletserver
    build:
      context: ./
      dockerfile: walletservice.dockerfile
    ports:
    - 8080:8080
    depends_on:
      - database
    links:
      - database
